[package]
name = "guardi-cli"
version = "0.0.1"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
trust-dns-server = "0.23"
trust-dns-resolver = "0.23"
async-trait = "0.1.89"
trust-dns-proto = "0.23.2"
colored = "3.1.1"
